
# Note: some manufactures have merged or renamed
# so this is not working in every case
# Notably: Senvion ...
MANUFACTURERS = {"Nordex": "Nordex",
                 "ENERCON": "Enercon",
                 "Vestas": "Vestas",
                 "Fuhrländer": "Fuhrländer",
                 "GE Wind Energy": "GE Wind Energy",
                 "GE Renewable Germany": "GE Renewable Germany",
                 "NEG Micon": "NEG Micon",
                 "Südwind": "Südwind",
                 "Schütz": "Schütz",
                 "Kenersys": "Kenersys",
                 "Siemens Gamesa": "Siemens Gamesa",
                 "Gamesa Corporación Tecnológica": "Gamesa",
                 "Siemens Windenergie GmbH": "Siemens Windenergie GmbH",
                 "REpower": "REpower",
                 "DeWind": "DeWind",
                 "Senvion": "Senvion",
                 "Tacke": "Tacke",
                 "Frisia": "Frisia",
                 "Vensys": "Vensys",
                 "Nordtank": "Nordtank",
                 "Enron": "Enron",
                 "General Electric": "General Electric",
                 "eno": "eno",
                 "AN Windenergie": "AN Windenergie",
                 "Jacobs": "Jacobs",
                 "HSW": "HSW",
                 "Lagerwey": "Lagerwey",
                 "Amperax": "Amperax",
                 "Adwen": "Adwen",
                 }

ENERGY_SOURCES = ["wind", "hydro", "biomass", "gsgk"]

GEOMETRY_COLS = {"geometry": "geometry"}
COMMON_COLS = {"Laengengrad": "lon",
               "Breitengrad": "lat",
               "EinheitMastrNummer": "ref:mastr",
               }

SELECT_COLS = {"EegMastrNummer": "ref:eeg",
               "InstallierteLeistung": "generator:output:electricity",
               "Nettonennleistung": "generator:output:electricity",
               "Inbetriebnahmedatum": "start_date",
               "GeplantesInbetriebnahmedatum": "opening_date",
               "DatumEndgueltigeStilllegung": "end_date",
               "Hersteller": "manufacturer",
               "Typenbezeichnung": "model",
               "Rotordurchmesser": "rotor:diameter",
               "Nabenhoehe": "height:hub",
               "NameStromerzeugungseinheit": "nameUnit",
               "Energietraeger": "energyCarrier",
               "Biomasseart": "typeOfBiomas",
               "Hauptbrennstoff": "mainFuel",
               "Hausnummer": "addr:housenumber",
               "Strasse": "addr:street",
               "Gemeinde": "municipality",
               "Landkreis": "county",
               "Bundesland": "state",
               "Technologie": "technology",
               "ArtDerWasserkraftanlage": "technology",
               "VerknuepfteEinheit": "connectedUnit",
               }
